// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9nfAJ7PDR6rVdZCdBu_mf2AjKcDtly74',
    appId: '1:121241823789:web:c12a6480707393e11ee6a4',
    messagingSenderId: '121241823789',
    projectId: 'airy-decorator-345705',
    authDomain: 'airy-decorator-345705.firebaseapp.com',
    storageBucket: 'airy-decorator-345705.appspot.com',
    measurementId: 'G-67K2EK25P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpyY2uuwnLG0UsRgJhDTkzThCHCUwiziE',
    appId: '1:121241823789:android:af65d51b7590ed2f1ee6a4',
    messagingSenderId: '121241823789',
    projectId: 'airy-decorator-345705',
    storageBucket: 'airy-decorator-345705.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsGoNG4XLQ-6WDuiDnao-kkriLxTTWb1Q',
    appId: '1:121241823789:ios:6c4bcec53a7a61dc1ee6a4',
    messagingSenderId: '121241823789',
    projectId: 'airy-decorator-345705',
    storageBucket: 'airy-decorator-345705.appspot.com',
    iosClientId: '121241823789-6prah2dsetat49782ueoh7njsu81q264.apps.googleusercontent.com',
    iosBundleId: 'com.example.strayFinder',
  );
}
